### ISSUE TITLE
bad segmentation in /tmp/base_chars.png

### ISSUE THREAD

**Issue by michath** [MichalBusta/FASText#10]
hi,
running tools/segmentation.py creates /tmp/base_chars.png:
- i was not able to determine where exactly in code it is created
- i guess it contains the resulted segmentation, which is bad
- i wonder if the bad result is due to an unfit cvBoostChar.xml
- which API should i use to recreate cvBoostChar.xml myself?
- any code example for such call?

thanks!!

**Comment by MichalBusta** [comment]
Hi,

On 08/16/2016 04:58 PM, michath wrote:

> hi,
> running tools/segmentation.py creates /tmp/base_chars.png:
> - i was not able to determine where exactly in code it is created
> 
> src/Python/pyFastText.cpp :  get_char_segmentations
> - i guess it contains the resulted segmentation, which is bad
> 
> the "chars" visualization is rubbish:
>      - works just on simple images : there are all segmenations from all 
> scales, bigger segmentations hides smaller etc.
> - i wonder if the bad result is due to an unfit cvBoostChar.xml
> 
> probably no, you can try just draw the bounding boxes of the 
> segmentations (first 4 columns in segmentation array).
> - which API should i use to recreate cvBoostChar.xml myself?
> 
> no API provided.

All the best, Michal

**Comment by michath** [comment]
thanks, but -
array (char) segmentations has ~2000 rows per source image given in figure 11 (top row) of the paper.
how can this number be narrowed down to produce the resulting text in figure 11 (bottom row)?
[i guess this large number explains  /tmp/base_chars.png]
thanks again :)

**Comment by michath** [comment]
thanks, but:
- where in code do i get the features for such classifier?
- the paper mentions four features, but cvBoostChar.xml has six.
- where in code do i get the output of AdaBoost? is it applied?

thanks a lot!

**Comment by MichalBusta** [comment]
On 08/17/2016 04:50 PM, michath wrote:

> thanks, but:
> - where in code do i get the features for such classifier?
> 
> CharClassifier.cpp -> extractCharFeatures
> - the paper mentions four features, but cvBoostChar.xml has six.
> 
> yes, the code evolved since publication deadline and release time. If 
> desired, I can publish change list. (there are also small changes in 
> pattern cheking, etc ... )
> - where in code do i get the output of AdaBoost? is it applied?
>   thanks a lot!
> 
> the output of classifier is in segmentations array:
> see quality -> returns the np array where row is:  [bbox.x, bbox.y, 
> bbox.width, bbox.height, keyPoint.pt.x, keyPoint.pt.y, octave, ?, 
> duplicate, quality, [keypointsIds]]

there is no filtering of the segmentations, you can just query for 
quality: segmentations[:, 9] > q
