### ISSUE TITLE
Segmentation Fault 

### ISSUE THREAD

**Issue by iamvc7** [MichalBusta/FASText#12]
Can anyone here please help me with this ?

This the output I got.

Using FT detector edgeThreshold = 13, kpTypes: 3
Using PyramidSegmenter, segmDeltaInt: 1
Loading CharCls Model from: /home/ubuntu/FASText/cvBoostChar.xml
New instance 0 with edge threshold: 13
Segmentation fault (core dumped)

**Comment by yuliok0715** [comment]
How did you solve that?
