### ISSUE TITLE
how to call getNormalizedLines functions

### ISSUE THREAD

**Issue by JuggYurnero** [MichalBusta/FASText#19]
Hi, Michal
I try to use your code to detect Chinese text, but I just can not find how to get the detected text lines. In the code, I found getNormalizedLines function, so I wanna ask is this function the proper function that can get the detected text lines, if so, how can I call this function?
Thanks very much~

**Comment by MichalBusta** [comment]
Hi Jugg,

On 11/24/2016 04:35 PM, JuggYurnero wrote:
>
> Hi, Michal
> I try to use your code to detect Chinese text, but I just can not find 
> how to get the detected text lines. In the code, I found 
> getNormalizedLines function, so I wanna ask is this function the 
> proper function that can get the detected text lines, if so, how can I 
> call this function?
>
Unfortunately, the public code so far contains just region detection. I 
still do not have permission to share the rest.

so quickest way woud be:
     - https://github.com/opencv/opencv_contrib/tree/master/modules/text
     - take e-r grouping part of the code

or just do the simple houg-like voting (fastest way is: each region 
votes for each line direction - with this simple approach and LSTM 
recognizer you shoud get about 77% recall on icdar 2013 dataset)

Michal

**Comment by JuggYurnero** [comment]
ok, got it, Thanks so much
