### ISSUE TITLE
Could not find "3.4. Text Clustering" in code 

### ISSUE THREAD

**Issue by hemanthkorrapati** [MichalBusta/FASText#2]
Hi 

I am trying to locate the part of the code that executes text clustering (Section 3.4 of your FasText paper in ICCV' 15). Could you please help pinpointing the source file and function(s) that perform this ?

Thank you

**Comment by MichalBusta** [comment]
Hi, 
the code for the text clustering is not released (yet).

**Comment by hemanthkorrapati** [comment]
Hi 

Thanks for the information. May I know when the code is expected to be released ? 
I just need it for experimental purposes and will in no way cause licensing issues (if that was a concern).

**Comment by MichalBusta** [comment]
Hopefully within 2 months. 
The main reason is that there are still some open issues (too many ad-hoc parameters etc.).

**Comment by Bunny10** [comment]
Hi @MichalBusta , Could you please let me know when would be possible date, to post the last module **3.4 Text clustering code** here ??
We are waiting .....

**Comment by Bunny10** [comment]
@MichalBusta  are you guys working on posting TextClustering code here ? Please let us know.

**Comment by MichalBusta** [comment]
Sorry for keeping you waiting.
we have still students working on more robust version.

Michal

**Comment by Bunny10** [comment]
Thanks for the reply @MichalBusta  . At-least let me know the expected date now if you could tell ?

**Comment by janmeier** [comment]
Just chiming in to say I'd be very interested in this as well

**Comment by Bunny10** [comment]
@MichalBusta  waiting for the updated code ;) are you guys ready..

**Comment by Bunny10** [comment]
@MichalBusta  any updates about text clustering code... would like to do for experimental purpose.

**Comment by MichalBusta** [comment]
Hi, will be decided on friday ... I'll let you know.

**Comment by PhilAndrew** [comment]
Hi, I notice the output of this is to produce many many weighted letter candidates as in this image I generated from your code. Can the text clustering code narrow down the results to just the text areas?

![lettercandidates](https://cloud.githubusercontent.com/assets/1852/17953903/d8044690-6aa9-11e6-9ce3-32b524326571.png)

**Comment by MichalBusta** [comment]
Hi,

On 08/25/2016 03:54 AM, philip andrew wrote:

> Hi, I notice the output of this is to produce many many weighted 
> letter candidates as in this image I generated from your code. Can the 
> text clustering code narrow down the results to just the text areas?
> 
> Depending on task, but generally no. Text clustering gives you about 75% 
> recall with 10% precision on icdar 2013 dataset with (almost) full 
> rotation invariance. We left the final decision/cutting to OCR 
> classifier (and this gives you just text areas).

Also note, that you get all segmentations from the image, so you can set 
up your working point on the ROC curve.

Michal

**Comment by Bunny10** [comment]
Hi @MichalBusta  How was the "Text Clustering module "testing going on??

**Comment by MichalBusta** [comment]
Simple grouping added: 
 - each region votes in all directions 
 - brute force solution (NMS left for ocr stage)
