### ISSUE TITLE
Text clustering

### ISSUE THREAD

**Issue by anhhoangta** [MichalBusta/FASText#20]
Hi,

After segment text successfully as in segmentation.py, any suggest about how to make text clustering?

Thanks!

**Comment by MichalBusta** [comment]
just pushed trivial version.

**Comment by MichalBusta** [comment]
alternative solutions: 
 - https://github.com/lluisgomez/TextProposals
 - classic version https://github.com/opencv/opencv_contrib/tree/master/modules/text (heuristic based ER grouping)
 - Text Flow: http://www.cv-foundation.org/openaccess/content_iccv_2015/papers/Tian_Text_Flow_A_ICCV_2015_paper.pdf

**Comment by anhhoangta** [comment]
Thanks for all! :D
