### ISSUE TITLE
in process_dir.cpp, strange code to write null image and cout null strings

### ISSUE THREAD

**Issue by jhyvictory** [MichalBusta/FASText#21]
cv::Mat strokes;
		std::string imgName = outDir;
		imgName += cmp::IOUtils::Basename(files[x]) + ".png";
		cv::imwrite(imgName,  strokes);

		std::vector<string> strings;
		std::vector<double> quality;
		for( auto str : strings)
		{
			std::cout << "Found: " << str << std::endl;
}

**Comment by MichalBusta** [comment]
Hi, sorry -  leftover from full pipeline with recognizer.
