### ISSUE TITLE
To detect only horizontal text lines，how to change the code？  

### ISSUE THREAD

**Issue by arestorres** [MichalBusta/FASText#22]
hi， @MichalBusta , in my case, only horizontal text lines is needed, how can I change ur code to do this? many thanks!

**Comment by MichalBusta** [comment]
Hi, 
you have so many options:
 - the method ft.findTextLines() returns also rotated rectangle points - so easy solution is to ignore all proposals based on angle. 
 - modify the voting (/ignore local maxima for angles outside search range = same result as previous, minor speed-up )
 - do the region grouping yourself  

Michal
