### ISSUE TITLE
I got many intra-lines when I use ft.findTextLines()

### ISSUE THREAD

**Issue by zarifazhu** [MichalBusta/FASText#24]
When I use 
   lines=ft.findTextLines()
then     
for i in range(lines.shape[0]):
       rectn = lines[i, :]
       rectn[2] += rectn[0]
       rectn[3] += rectn[1];  
        cv2.rectangle(img,(rectn[0],rectn[1]),(rectn[2],rectn[3]), color)        
        cv2.imwrite('dst.jpg',img);  

I got many intra lines in the pic "img", how can i remove those lines?

**Comment by MichalBusta** [comment]
Hi, 
depends on the task / constraints:
  - if you want "unconstrained" text detection, best solution is so-far brute-force: do the OCR and pick the best based on language model.
