### ISSUE TITLE
Line Detector Issue

### ISSUE THREAD

**Issue by BurhanUlTayyab** [MichalBusta/FASText#28]
HI! 

When I try to run, testlines.py, I get this issue

OpenCV Error: Assertion failed (total >= 0 && (depth == CV_32F || depth == CV_32S)) in convexHull, file /home/burhan/cv/opencv/modules/imgproc/src/convhull.cpp, line 136
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/burhan/cv/opencv/modules/imgproc/src/convhull.cpp:136: error: (-215) total >= 0 && (depth == CV_32F || depth == CV_32S) in function convexHull

I'm using OPENCV 3.2.0 for Linux

Please help me solve the issue

Thanks
Burhan Ul Tayyab

**Comment by MichalBusta** [comment]
Hi, 
can you share data?

**Comment by BurhanUlTayyab** [comment]
Solved it, it was OPENCV Problem, found that it only works with OPENCV v2., OPENCV v3 gives that error.
Thanks by the way!!!!!!!!!!!

**Comment by vinodhian** [comment]
But is there a way to fix the issue in openCV v3?
