### ISSUE TITLE
cvBoostChar.xml file

### ISSUE THREAD

**Issue by zacniewski** [MichalBusta/FASText#29]
Hi Michal!
Is there any description how to train the classifier?
Or the only option is to carefully analyze the code?

Best regards
Artur

**Comment by MichalBusta** [comment]
Hello Artur,

the training part is not public (I'll share code if you are interested).

It's simple - we are using OpenCV stuff, so just detect regions, select 
based on IoU with GT and train boost classifier.

Micha

**Comment by zacniewski** [comment]
Hi Michal,
It would be nice, if you can share this code for me. Of course I'm very interested.
I'd like to investigate FASText in more detailed way, so if you can share the code for a.zacniewski@gmail.com it will be fantastic. Maybe I'll find some interesting ways to improve 
the FASText :)

Best regards
Artur

**Comment by zacniewski** [comment]
Thanks for sharing the code :)
