### ISSUE TITLE
 error: ‘featuresMultiChar’ was not declared in this scope

### ISSUE THREAD

**Issue by blakeliu** [MichalBusta/FASText#30]
**error: ‘featuresMultiChar’ was not declared in this scope
  createTrainDataMat(featuresMultiChar, labesMultiChar, trainingData2, labelsMat2);
                     ^
/home/blake/cv/text/FASText/src/Python/pyFastTextG.cpp:816:40: error: ‘labesMultiChar’ was not declared in this scope
  createTrainDataMat(featuresMultiChar, labesMultiChar, trainingData2, labelsMat2);**

my opencv version: 2.4.13
where is createTrainDataMat defined?

**Comment by MichalBusta** [comment]
build should be fixed for opencv 2.4 now.
