### ISSUE TITLE
How  Can i transform detector output to character?

### ISSUE THREAD

**Issue by WangShuaiHefei** [MichalBusta/FASText#31]
Hello Mr.Neumann,
        I am a student  ,interesting in your Excellent work on FASText. Infact i am a novice in Ocr area.I run your code,and get the corresponding output .Now i dont know how to transform the output to character.Is there any public code or program which can work it out? 

Please suggest the solutions,
Regards

**Comment by MichalBusta** [comment]
Hi, 
you have so many options, the choice depends on application, so I just make quick subset:
 - you can use OS OCR (tesserract/...)
 - you can use photoOCR works published: 

https://github.com/tmbdev/clstm
https://github.com/da03/Attention-OCR
https://github.com/MichalBusta/DeepTextSpotter (ocr network part)
.... so many others 

- you can write your own recognizer for constrained solution. 

Hope this helps. All the best, Michal
