### ISSUE TITLE
Train a Text-Line detector/ extractor

### ISSUE THREAD

**Issue by ghost** [MichalBusta/FASText#39]
@MichalBusta Thank you for your hard work
How can I train and extract text-lines? I only need the cropped images of the text-lines.

**Comment by MichalBusta** [comment]
The splitting into the lines is pure heuristic - no training needed. 
You can modify code in https://github.com/MichalBusta/FASText/blob/master/src/HoughTLDetector.cpp 
 -- see "spacing"
