### ISSUE TITLE
need a readme file for building this project in MS visual studio

### ISSUE THREAD

**Issue by Bunny10** [MichalBusta/FASText#4]

**Comment by Bunny10** [comment]
I'm trying to build this project using visual studio 2013, can anyone upload the MS visual studio application of current project here??

**Comment by Bunny10** [comment]
I'm trying to build this project using visual studio 2013, can anyone upload the MS visual studio application of current project here??

**Comment by PhilAndrew** [comment]
I will upload a visual studio 2013 but even when its built in visual studio 2013, some of the code is in Python so that code in Python doesn't run
