### ISSUE TITLE
No module named ftext

### ISSUE THREAD

**Issue by tyrion94** [MichalBusta/FASText#5]
Hello I am using ubuntu  with opencv 3.1.0 after building the executables I am trying to run the toy example I am getting this error. 

atul@ubuntu:~/Desktop/FASText-master/tools$ python segmentation.py ~/Desktop/1

/home/atul/Desktop/FASText-master
Traceback (most recent call last):
  File "segmentation.py", line 10, in <module>
    from ft import FASTex
  File "/home/atul/Desktop/FASText-master/tools/ft.py", line 19, in <module>
    import ftext
ImportError: No module named ftext

**Comment by MichalBusta** [comment]
Hi,
checklist:  
- are you using python 2.?
- if yes,  can you locate file ftext.so? 

if no, check cmake/make output
if yes, run python in directory where ftext.so is and execute: 

import sys
sys.path.append('.')
import ftext 

if this work, just check if if your build directory is proper name ( {fastext_Dir}/Release) or just modify sys.path to contain lib directory.

**Comment by GYXie** [comment]
Hi, I am getting the same error. I am using python 2.7 and I cann't find ftext.so in the Release dir. I am a python newbie. How could I fix this problem? 

Thanks.

**Comment by cyf520** [comment]
I cann't locate file ftext.so. How to check cmake/make output?
Thanks!

**Comment by mpvphd** [comment]
I am getting the same error too. I am using python 2.7 on macosx.
How may I check cmake/make output?
Thanks!

Find command gave me a directory :
> find ./ -iname ftext*
.//Release/src/Python/CMakeFiles/ftext.dir

Ls command on this gives :
> ls .//Release/src/Python/CMakeFiles/ftext.dir
DependInfo.cmake
cmake_clean.cmake	
flags.make		
progress.make
build.make		
depend.make		
link.txt

cmake command in Release gives :
> cmake -D CMAKE_BUILD_TYPE=Release ..
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) (found version "1.0")
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) (found version "1.0")
-- Using OpenCV from /usr/local/share/OpenCV, include dirs: /usr/local/include;/usr/local/include/opencv 3
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.
  **MACOSX_RPATH is not specified for the following targets:**
   **ftext**
This warning is for project developers.  Use -Wno-dev to suppress it.
-- Generating done
-- Build files have been written`

**Comment by YileenOng** [comment]
Hi,

I am facing the same issue, cannot find ftext module (import ftext).
I am using Python 2.7.14 on windows, but i cant find where the file ftext.so is located.
Is the file ftext.so attached in the downloaded file? I cant find it.
May i know how to check check cmake/make output as well?
Thank you!

Yileen

**Comment by MichalBusta** [comment]
Hi, Yileen, 
on windows, the extension is not .so, but .dll.
