### ISSUE TITLE
module ftext is missing

### ISSUE THREAD

**Issue by rap9430** [MichalBusta/FASText#6]
I cannot find the ftext module (import ftext). Am i missing something? thanks....

**Comment by MichalBusta** [comment]
Hi,

checklist:

are you using python 2.?
if yes, can you locate file ftext.so?
if no, check cmake/make output
if yes, run python in directory where ftext.so is and execute:

import sys
sys.path.append('.')
import ftext

if this work, just check if if your build directory is proper name ( 
{fastext_Dir}/Release) or just modify sys.path to contain lib directory.

**Comment by MichalBusta** [comment]
Please search issues history.

**Comment by jsaisagar** [comment]
Hi,

I am also facing the same issue. cmake and make output seems to be fine. ".so" file is not created while "ftext.dylib" file is created in Release folder. I am using Mac el capitan.

May I know how to proceed. 
Thanks..

**Comment by MichalBusta** [comment]
Hello,
same checklist:
https://github.com/MichalBusta/FASText/issues/6
- on Mac extension is dylib insead of so.
  Michal

**Comment by jsaisagar** [comment]
Thanks Busta for the prompt reply. After following the above steps and when import ftext is ran in python, I am getting the following error.

"Fatal Python error: PyThreadState_Get: no current thread"

May I know why is this occuring?

**Comment by MichalBusta** [comment]
Hi,
I'm not expert, but here can be the description what is happening:

http://stackoverflow.com/questions/15678153/homebrew-python-on-mac-os-x-10-8-fatal-python-error-pythreadstate-get-no-cu

(in short - cmake finds system python, and you are using homebrew)

on the CMakeLists in Python directory, there is work-around for one of ours MAC books. (section FLIPAJS_PC), so you can try if it will work for you.

All the best, Michal

**Comment by Jaykob** [comment]
I had the same problem on OS X. Renaming ftext.dylib to ftext.so fixed the problem for me. Admitted, it isn't the nicest workaround...

**Comment by mattmezza** [comment]
How is it called the library on Windows?

**Comment by MichalBusta** [comment]
dll or pyd?

**Comment by mattmezza** [comment]
Great! So my msbuild did not generate any library, that's why the module is not found.

**Comment by YileenOng** [comment]
Hi, 

I am facing the same issue, cannot find ftext module (import ftext). 
I am using Python 2.7.14, but i cant find where the file ftext.so is located.
Is the file ftext.so attached in the downloaded file? I cant find it.
May i know how to check check cmake/make output as well? 
Thank you!

Yileen
